Update vendoring for k8s 1.19
kubevirt/cloud-provider-kubevirt pull request #13
Opened 2020-10-22 14:09 UTC by gonzolino

2020-10-22 14:12 UTC, afritzler commented
/cc @stoyanr

We are currently rewriting the cloud controller to use the controller runtime client + that way bumping the k8s version to 1.19. Still WIP though.

2020-10-27 14:52 UTC, stoyanr requested changes
@gonzolino @afritzler Thanks a lot for addressing this! The PR looks good, however when I cloned it locally and tried to build it I encountered some issues, mainly with missing `package` in tests files, as well as with some build errors due to incorrect dependencies. I fixed them locally, you can see the changes I did here: https://github.com/stoyanr/cloud-provider-kubevirt/commit/fa0e55aa8c3f7557577c04c9d3d222295e561ccc. I tried to push this commit to this PR but permission was denied.
Are you going to refactor also the tests? Should I build and test the updated CCM with our kubevirt extension?

2020-10-27 15:15 UTC, afritzler commented
This is still WIP.  So there are still glitches. The coding should build now - but we still need to refactor the testing/mocking infrastructure. That is actually a little bit trickier.

2020-10-27 16:01 UTC, stoyanr commented
@afritzler The coding doesn't build without the last commit from my fork - as you can see Travis build also fails. You need the commit I pointed above for it to build.
In addition, after I got it to build, I tested it with our kubevirt extension and found some loadbalancer creation issues. See https://github.com/stoyanr/cloud-provider-kubevirt/commit/88c511bf7968e5cbc3caba6e9a5e42eade073285 for the fixes I had to do. With these fixes, the CCM seems to work as expected.
If you give me permissions, I could push these 2 commits to the PR as well. Or you could do the same changes yourselves.

2020-10-27 16:11 UTC, stoyanr requested changes

2020-10-27 16:11 UTC, stoyanr commented on go.mod
> +	google.golang.org/grpc/examples v0.0.0-20201021230544-4e8458e5c638 // indirect
This should not be here for `make deps-update` to pass
```suggestion
```

2020-10-27 16:11 UTC, stoyanr commented on go.mod
> +	k8s.io/api => k8s.io/api v0.19.3
You have to pin gopkg.in/square/go-jose.v2 to v2.2.2 or you will get errors during build in k8s deps.
```suggestion
	google.golang.org/grpc => google.golang.org/grpc v1.27.0
	gopkg.in/square/go-jose.v2 => gopkg.in/square/go-jose.v2 v2.2.2
	k8s.io/api => k8s.io/api v0.19.3
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/cloud_test.go
> +// package kubevirt
Uncomment this for the build to pass.
```suggestion
package kubevirt
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/instances_test.go
> +// package kubevirt
Uncomment this for the build to pass.
```suggestion
package kubevirt
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/loadbalancer.go
> +	if err := lb.client.Get(ctx, client.ObjectKey{Name: lbName, Namespace: lb.namespace}, service); err != nil {
You can't pass a nil pointer here,
```suggestion
	var service corev1.Service
	if err := lb.client.Get(ctx, client.ObjectKey{Name: lbName, Namespace: lb.namespace}, &service); err != nil {
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/loadbalancer.go
>  	return service, true, nil
```suggestion
	return &service, true, nil
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/loadbalancer.go
>  	vmiUIDs := make([]string, len(instanceIDs))
Don't use make, or you will get a slice with a few empty strings inside, this breaks validation later on.
```suggestion
	var vmiUIDs []string
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/loadbalancer_test.go
> +// package kubevirt
```suggestion
package kubevirt
```

2020-10-27 16:11 UTC, stoyanr commented on pkg/cloudprovider/kubevirt/zones_test.go
> +// package kubevirt
```suggestion
package kubevirt
```

2020-10-28 13:47 UTC, gonzolino commented
> If you give me permissions, I could push these 2 commits to the PR as well. Or you could do the same changes yourselves - I suggested the important ones below.

Thanks @stoyanr ! I cherry-picked your changes into the PR. @afritzler and I will now try to update the unit tests for the new controller-runtime client.

2020-10-28 14:34 UTC, stoyanr commented
@gonzolino, I am glad to be able to help, though I still don't understand how do you manage to build anything without the other changes proposed above. In any case, looking forward to the updated PR.

2021-02-04 17:13 UTC, gonzolino commented
/remove-lifecycle stale

2021-03-31 07:16 UTC, stoyanr approved these changes

2021-03-31 10:37 UTC, gonzolino commented
@stoyanr I wanted to merge #14 before finishing this PR. I currently don't have much time to work on this, but I'll try to make some progress over Easter.

2021-04-06 13:15 UTC, merged